### ISSUE TITLE
Anonymous turtle is not working?

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#631]
Maybe it is just my faulty memory but I thought that

```
from turtle import *
forward(10)
```

used to work?  I see evidence of an anonymous turtle in the code but can't make it work.

Brad

**Comment by waywaaard** [comment]
I can conform this. @bnmnetp Do you get this error?

```
wrapped method failed
VM183:2083 TypeError: Cannot read property 'apply' of undefined
    at wrapperFn (eval at y (skulpt.min.js:1021), <anonymous>:2079:42)
    at Sk.builtin.func.tp$call (skulpt.min.js:163)
    at Object.Sk.misceval.applyOrSuspend (skulpt.min.js:280)
    at Object.Sk.misceval.callsimOrSuspend (skulpt.min.js:271)
    at $scope99 (eval at y (skulpt.min.js:1021), <anonymous>:19:118)
    at eval (eval at y (skulpt.min.js:1021), <anonymous>:30:1)
    at y (skulpt.min.js:1021)
    at Object.Sk.importModuleInternal_ (skulpt.min.js:1022)
    at Object.Sk.importMainWithBody (skulpt.min.js:1023)
```

**Comment by bnmnetp** [comment]
In my online text I get the following:   We don't show the full stack track...

```
ExternalError: TypeError: undefined is not an object (evaluating 'instance[method].apply') on line 3
```

Looks like the same basic error to me.

**Comment by bnmnetp** [comment]
Right, it does seem like its been around for at least as long as the last update to skulpt.org

**Comment by albertjan** [comment]
Oh bah! that sucks.

**Comment by albertjan** [comment]
It fails here: https://github.com/skulpt/skulpt/blob/master/src/lib/turtle.js#L2079

**Comment by albertjan** [comment]
if you change that to `instance.instance[method]` it does work... but don't ask me why this happened.

**Comment by bnmnetp** [comment]
Hmm, interesting.  Does that break other stuff??

**Comment by albertjan** [comment]
@bnmnetp I think it might we may need to change the `ensureAnonymous` function but I still don't understand what happened.

**Comment by bnmnetp** [comment]
@albertjan I tried the change you mentioned, but that still ends up with an error:

```
ExternalError: TypeError: this.queueMoveBy is not a function. (In 'this.queueMoveBy(this._x, this._y, this._radians, distance)', 'this.queueMoveBy' is undefined) on line 3
```

**Comment by bnmnetp** [comment]
I don't understand what happened either, and I haven't had the chance to do the "git bisect" dance to go back and figure out what commit broke things.

**Comment by libremente** [comment]
@albertjan sorry to reopen but I still have problems on this:
```python
from turtle import *
forward(10)
```
returns:
`ExternalError: TypeError: a is undefined on line 3`

Skulpt 0.11.1 from npm.
Thanks!
